### ISSUE TITLE
Module not listed after installation

### ISSUE THREAD

**Issue by Flightkick** [nebula-it/New-TalosVM#1]
Without a Powershell manifest file, the module might not be available.

**Steps to reproduce:**
1. Install the module in `C:\Program Files\WindowsPowerShell\Modules\Talos\1.0.0\`
2. Run `Get-Module -ListAvailable`
3. The `New-TalosVM` module/function is not listed.

**Comment by nebula-it** [comment]
Thank you for teaching me how to do it properly.🙂  I've been using the crude method of creating folder with the same name as function.

**Comment by Flightkick** [comment]
You're welcome! I didn't know either before I tried to get this module to work, so we both learned something new. 🙂
